# Generated by Django 5.1.2 on 2024-11-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('plan_deadline', 'Plan_deadline'), ('daily_achievement', 'Daily_achievement'), ('brag', 'Barg'), ('cheering', 'Cheering'), ('add_friend', 'Add_friend'), ('vote', 'Vote'), ('promise_accept', 'Promise_accept'), ('promise_completed', 'Promise_completed')], default='plan', max_length=20),
        ),
    ]
